---
- name: Setup Yii2 App Environment with Docker, Swarm, and NGINX
  hosts: all
  become: yes
  vars:
    yii2_container_port: 8080  # Adjust to match your Yii2 app container's exposed port

  tasks:

    # ----------------------------
    # Install Docker and Docker Compose
    # ----------------------------
    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: true

    # ----------------------------
    # Install NGINX, Git, and PHP
    # ----------------------------
    - name: Install NGINX, Git, PHP
      apt:
        name:
          - nginx
          - git
          - php-cli
          - php-mbstring
          - php-xml
        state: present

    - name: Ensure NGINX is started
      service:
        name: nginx
        state: started
        enabled: true

    # ----------------------------
    # Initialize Docker Swarm
    # ----------------------------
    - name: Initialize Docker Swarm
      shell: docker swarm init
      args:
        creates: /var/lib/docker/swarm
      register: swarm_result
      ignore_errors: true

    # ----------------------------
    # Configure NGINX as reverse proxy
    # ----------------------------
    - name: Create NGINX config for Yii2 app
      copy:
        dest: /etc/nginx/sites-available/yii2
        content: |
          server {
              listen 80;
              server_name _;
              location / {
                  proxy_pass http://127.0.0.1:{{ yii2_container_port }};
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Enable Yii2 site config
      file:
        src: /etc/nginx/sites-available/yii2
        dest: /etc/nginx/sites-enabled/yii2
        state: link
        force: true

    - name: Remove default NGINX config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Reload NGINX
      service:
        name: nginx
        state: reloaded
