name: PearlThought

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build the image
        run: |
            set -x
            docker build -t pearl .
            docker tag pearl golushbz/pearl:latest

      - name: push the image
        run: |
            docker push golushbz/pearl:latest
            echo "images pushed"
            
